mj:
  discord:
    guild-id: 1128187197099618386
    channel-id: 1128187197556785223
    user-token: MTAyMTUzNDI0MDI1NDQ2MDAxNQ.Gk7MDj.opAPMEWjC0DYfRQ-RjetiY0hnWCf6C7A3xc_jU
    session-id: 69382be819fc62a882c8e4d22e86d58b
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0
    user-wss: true
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: baidu
  baidu-translate:
      appid: 20230715001745696
      app-secret: G0GwiA7iY3TwfzoL2_04
  queue:
    timeout-minutes: 5
    core-size: 3
    queue-size: 10
