mj:
  discord:
    guild-id: xxx
    channel-id: xxx
    user-token: xxx
    session-id: xxx
    user-agent: xxx
    user-wss: true
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: baidu
  baidu-translate:
      appid: xxx
      app-secret: xxx
  queue:
    timeout-minutes: 5
    core-size: 3
    queue-size: 10
